name: Update README
on:
  push:
    branches: ["main"]
  
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bitflight-devops/github-action-readme-generator@v1.0.12
        with:
          action: "action.yml"
          readme: "README.md"
          owner: "blinkhealth"
          repo: "atlantis-gh-action"
          pretty: "prettier"
          version_prefix: "v"
          title_prefix: "GitHub Action:"